"""set email unique

Revision ID: e938057e12fb
Revises: 671507f4446f
Create Date: 2023-08-13 18:16:49.638685

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e938057e12fb'
down_revision: Union[str, None] = '671507f4446f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('device_user_id_fkey', 'device', type_='foreignkey')
    op.create_foreign_key(None, 'device', 'user', ['user_id'], ['id'], source_schema='public', referent_schema='public')
    op.drop_constraint('group_device_id_fkey', 'group', type_='foreignkey')
    op.drop_constraint('group_user_id_fkey', 'group', type_='foreignkey')
    op.create_foreign_key(None, 'group', 'device', ['device_id'], ['id'], source_schema='public', referent_schema='public')
    op.create_foreign_key(None, 'group', 'user', ['user_id'], ['id'], source_schema='public', referent_schema='public')
    op.create_unique_constraint(None, 'user', ['email'], schema='public')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', schema='public', type_='unique')
    op.drop_constraint(None, 'group', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'group', schema='public', type_='foreignkey')
    op.create_foreign_key('group_user_id_fkey', 'group', 'user', ['user_id'], ['id'])
    op.create_foreign_key('group_device_id_fkey', 'group', 'device', ['device_id'], ['id'])
    op.drop_constraint(None, 'device', schema='public', type_='foreignkey')
    op.create_foreign_key('device_user_id_fkey', 'device', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###
